apiVersion: v2
name: tiddlywiki
description: A Helm chart for Kubernetes to deploy elasticdog/tiddlywiki
version: 0.1.0
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: creation